14 hp system
alex-mike-mark-again/tower-offense pull request #20
Opened 2022-08-25 20:30 UTC by alex-mike-mark-again

Work in progress! Closes #14

2022-08-25 20:31 UTC, alex-mike-mark-again commented on TowerOffense/PlayerManager.cs
> +        public PlayerManager() {}
Whoops, this should still be private. No desire to have anything create this thing cuz it's a singlton

2022-08-26 15:51 UTC, alex-mike-mark-again commented on TowerOffense.Objects/HPDisplay.cs
> +            _font = TOGame.Instance.Content.Load<SpriteFont>("Fonts/HpDisplay");
I'll add something about handling fonts in the asset manager issue.

2022-08-26 15:51 UTC, alex-mike-mark-again commented on Content/Content.mgcb
> +#begin Fonts/HpDisplay.spritefont
I am calling this `HpDisplay` over the font name because I'd like the settings in the sprintfont file to reflect just what the HP Display looks like. I have suspicions there are better ways to do it, but this gets me the ability to tweak it without influencing other things I want.

2022-08-26 16:32 UTC, froghood requested changes

2022-08-26 16:32 UTC, froghood commented on TowerOffense.Objects/HPDisplay.cs
> +            TOGame.SpriteBatch.DrawString(_font, _text, position, Color.Red);
#23

2022-08-26 16:32 UTC, froghood commented on TowerOffense.Objects/HPDisplay.cs
> +            _font = TOGame.Instance.Content.Load<SpriteFont>("Fonts/HpDisplay");
yes assets should all probably be loaded in `TOGame.LoadContent`

2022-08-26 16:32 UTC, froghood commented on TowerOffense/PlayerManager.cs
> +using TowerOffense;
it might be better to not go with a strict singleton approach but to instead have `PlayerManager` be owned and accessed through `TOGame.PlayerManager`. it also keeps it consistent with our other service like objects

2022-08-26 16:34 UTC, alex-mike-mark-again commented on TowerOffense/PlayerManager.cs
> +using TowerOffense;
Works for me 👍

2022-08-26 16:36 UTC, froghood commented on Content/Content.mgcb
> +#begin Fonts/HpDisplay.spritefont
i dont really understand but i trust u

2022-08-26 21:56 UTC, froghood reviewed
send it

2022-08-26 21:57 UTC, froghood approved these changes
send it again

2022-08-26 21:57 UTC, merged